import { describe, it, expect } from 'vitest';
import { classifyFile, isTest, isSource, isGenerated, isVendored } from '../../src/index/file-roles.js';

describe('classifyFile', () => {
  // Tier 1: Path-based
  it('classifies CI files', () => {
    expect(classifyFile('.github/workflows/ci.yml')).toBe('ci');
    expect(classifyFile('.circleci/config.yml')).toBe('ci');
  });

  it('classifies vendored files', () => {
    expect(classifyFile('vendor/lib/foo.js')).toBe('vendored');
    expect(classifyFile('node_modules/express/index.js')).toBe('vendored');
    expect(classifyFile('third_party/lib.c')).toBe('vendored');
  });

  it('classifies test files by directory', () => {
    expect(classifyFile('tests/test_app.py')).toBe('test');
    expect(classifyFile('test/utils.js')).toBe('test');
    expect(classifyFile('__tests__/component.test.js')).toBe('test');
    expect(classifyFile('spec/models/user_spec.rb')).toBe('test');
  });

  it('classifies docs files by directory', () => {
    expect(classifyFile('docs/api.md')).toBe('docs');
    expect(classifyFile('documentation/guide.rst')).toBe('docs');
  });

  it('classifies example files', () => {
    expect(classifyFile('examples/demo.py')).toBe('examples');
    expect(classifyFile('samples/basic.js')).toBe('examples');
  });

  it('classifies script files', () => {
    expect(classifyFile('scripts/deploy.sh')).toBe('scripts');
    expect(classifyFile('bin/run.js')).toBe('scripts');
  });

  it('classifies build output', () => {
    expect(classifyFile('build/output.js')).toBe('build');
    expect(classifyFile('dist/bundle.js')).toBe('build');
  });

  // Tier 2: Filename-based
  it('classifies build system files', () => {
    expect(classifyFile('Makefile')).toBe('build');
    expect(classifyFile('Dockerfile')).toBe('build');
    expect(classifyFile('webpack.config.js')).toBe('build');
    expect(classifyFile('vite.config.ts')).toBe('build');
  });

  it('classifies docs by filename prefix', () => {
    expect(classifyFile('README.md')).toBe('docs');
    expect(classifyFile('LICENSE')).toBe('docs');
    expect(classifyFile('CHANGELOG.md')).toBe('docs');
    expect(classifyFile('CONTRIBUTING.md')).toBe('docs');
  });

  it('classifies test files by filename pattern', () => {
    expect(classifyFile('src/app.test.js')).toBe('test');
    expect(classifyFile('src/utils.spec.ts')).toBe('test');
    expect(classifyFile('test_calculator.py')).toBe('test');
    expect(classifyFile('calculator_test.py')).toBe('test');
    expect(classifyFile('handler_test.go')).toBe('test');
    expect(classifyFile('AppTest.java')).toBe('test');
    expect(classifyFile('UserTest.cls')).toBe('test');
  });

  it('classifies data files', () => {
    expect(classifyFile('assets/logo.png')).toBe('data');
    expect(classifyFile('fonts/arial.woff2')).toBe('data');
  });

  it('classifies doc extensions', () => {
    expect(classifyFile('notes.md')).toBe('docs');
    expect(classifyFile('guide.rst')).toBe('docs');
  });

  it('classifies config files', () => {
    expect(classifyFile('package.json')).toBe('config');
    expect(classifyFile('tsconfig.json')).toBe('config');
    expect(classifyFile('.gitignore')).toBe('config');
    expect(classifyFile('pyproject.toml')).toBe('config');
  });

  it('classifies generated files', () => {
    expect(classifyFile('api.generated.ts')).toBe('generated');
    expect(classifyFile('model.pb.go')).toBe('generated');
    expect(classifyFile('service_pb2.py')).toBe('generated');
  });

  // Tier 3: Content-based
  it('classifies generated by content markers', () => {
    expect(classifyFile('src/api.js', '// DO NOT EDIT - auto-generated\nconst x = 1;')).toBe('generated');
    expect(classifyFile('src/api.js', '/* @generated */\nmodule.exports = {};')).toBe('generated');
  });

  it('classifies scripts by shebang', () => {
    expect(classifyFile('run', '#!/usr/bin/env node\nconsole.log("hi");')).toBe('scripts');
    expect(classifyFile('deploy', '#!/bin/bash\necho hi')).toBe('scripts');
  });

  it('falls through to source for normal files', () => {
    expect(classifyFile('src/app.js')).toBe('source');
    expect(classifyFile('lib/utils.py')).toBe('source');
    expect(classifyFile('main.go')).toBe('source');
    expect(classifyFile('App.java')).toBe('source');
  });
});

describe('isTest', () => {
  it('returns true for test files', () => {
    expect(isTest('tests/test_app.py')).toBe(true);
    expect(isTest('src/app.test.js')).toBe(true);
    expect(isTest('handler_test.go')).toBe(true);
  });

  it('returns false for non-test files', () => {
    expect(isTest('src/app.js')).toBe(false);
    expect(isTest('main.py')).toBe(false);
  });
});

describe('isSource', () => {
  it('returns true for source files', () => {
    expect(isSource('src/app.js')).toBe(true);
  });

  it('returns false for non-source files', () => {
    expect(isSource('tests/test_app.py')).toBe(false);
    expect(isSource('README.md')).toBe(false);
  });
});

describe('isGenerated', () => {
  it('detects generated files', () => {
    expect(isGenerated('api.generated.ts')).toBe(true);
    expect(isGenerated('src/api.js', '// DO NOT EDIT\nfoo')).toBe(true);
  });

  it('returns false for normal files', () => {
    expect(isGenerated('src/app.js')).toBe(false);
  });
});

describe('isVendored', () => {
  it('detects vendored paths', () => {
    expect(isVendored('vendor/lib.js')).toBe(true);
    expect(isVendored('node_modules/x/y.js')).toBe(true);
  });

  it('returns false for non-vendored', () => {
    expect(isVendored('src/app.js')).toBe(false);
  });
});
